Repository ssg-240304-java2/wms-justdo, pull requests merged in 2024-05, with the labels that each got.

#13 Feature : 기본 프로젝트 틀 작성
  .idea/.gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/justdo/fruitfruit/common/MyBatisTemplate.java
  src/main/java/com/justdo/fruitfruit/common/constant/Auth.java
  src/main/java/com/justdo/fruitfruit/common/constant/Status.java
  src/main/java/com/justdo/fruitfruit/controller/InputReader.java
  src/main/java/com/justdo/fruitfruit/controller/InputReaderFactory.java
  src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
  src/main/java/com/justdo/fruitfruit/run/Run.java
  src/main/java/com/justdo/fruitfruit/view/MainMenu.java
  src/main/java/com/justdo/fruitfruit/view/ResultMessage.java
  src/main/resources/config/connection-info.properties
  src/main/resources/config/mybatis-config.xml
Labels: ✨ Feature

#27 #16 판매자 알림 조회
  src/main/java/com/justdo/fruitfruit/NotificationMapper.java
  src/main/java/com/justdo/fruitfruit/model/DTO/NotificationDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
  src/main/java/com/justdo/fruitfruit/model/service/SellerService.java
  src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
  src/main/resources/com/justdo/fruitfruit/NotificationMapper.xml
Labels: ✨ Feature

#35 Featur : 프로젝트 구성 설정, 입고요청 메뉴개발
  .gitignore
  src/main/java/com/justdo/fruitfruit/common/MyBatisTemplate.java
  src/main/java/com/justdo/fruitfruit/common/constant/Auth.java
  src/main/java/com/justdo/fruitfruit/common/constant/Status.java
  src/main/java/com/justdo/fruitfruit/controller/WarehouseController.java
  src/main/java/com/justdo/fruitfruit/model/dao/WarehouseMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
  src/main/java/com/justdo/fruitfruit/run/Run.java
  src/main/java/com/justdo/fruitfruit/view/MainMenu.java
  src/main/java/com/justdo/fruitfruit/view/ResultMessage.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseResultMessage.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/warehouse/WarehouseMapper.xml
Labels: ✨ Feature

#36 #15 Feat : 판매자 상품 관리 기능 개발
  src/main/java/com/justdo/fruitfruit/NotificationMapper.java
  src/main/java/com/justdo/fruitfruit/controller/ProductController.java
  src/main/java/com/justdo/fruitfruit/model/dao/ProductMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/CategoryDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/NotificationDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/ProductService.java
  src/main/java/com/justdo/fruitfruit/model/service/SellerService.java
  src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
  src/main/java/com/justdo/fruitfruit/view/ProductResultMessage.java
  src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
  src/main/resources/com/justdo/fruitfruit/NotificationMapper.xml
  src/main/resources/sql/seller/ProductMapper.xml
Labels: ✨ Feature

#37 #19 청구금 조회 기능
  src/main/java/com/justdo/fruitfruit/NotificationMapper.java
  src/main/java/com/justdo/fruitfruit/model/dao/BillingMapper.java
  src/main/java/com/justdo/fruitfruit/model/dao/NotificationMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/OrderDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/SellerService.java
  src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
  src/main/resources/sql/seller/BillingMapper.xml
  src/main/resources/sql/seller/NotificationMapper.xml
Labels: ✨ Feature

#39 Feature : #14 입고 기능 개발, #20 재고 조회 기능 개발
  src/main/java/com/justdo/fruitfruit/controller/WarehouseController.java
  src/main/java/com/justdo/fruitfruit/model/dao/WarehouseMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/GradeDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/SectorDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
  src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseResultMessage.java
  src/main/resources/config/connection-info.properties
  src/main/resources/sql/warehouse/WarehouseMapper.xml
Labels: ✨ Feature

#40 #17 feat: 구매자 회원기능 개발
  src/main/java/com/justdo/fruitfruit/controller/CategoryController.java
  src/main/java/com/justdo/fruitfruit/controller/ProductController.java
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/CategoryMapper.java
  src/main/java/com/justdo/fruitfruit/model/dao/ProductMapper.java
  src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/CategoryDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/UserDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/CategoryService.java
  src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
  src/main/java/com/justdo/fruitfruit/model/service/ProductService.java
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/CategoryResultMessage.java
  src/main/java/com/justdo/fruitfruit/view/MainMenu.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/seller/ProductMapper.xml
  src/main/resources/sql/user/CategoryMapper.xml
  src/main/resources/sql/user/ProductMapper.xml
  src/main/resources/sql/user/UserMapper.xml
Labels: ✨ Feature

#43 #42 Fix: 로그인 기능 수정
  src/main/java/com/justdo/fruitfruit/controller/CompanyController.java
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/CompanyMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/CompanyDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/CompanyService.java
  src/main/java/com/justdo/fruitfruit/view/CompanyResultMessage.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/user/CompanyMapper.xml
  src/main/resources/sql/user/UserMapper.xml
Labels: ✨ Feature, 🐞 BugFix

#46 Feature : #20 상품명으로 재고조회 기능 완료
  src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
  src/main/resources/sql/warehouse/WarehouseMapper.xml
Labels: ✨ Feature

#47 Feature : #41 판매자 전환 기능 완료
  src/main/java/com/justdo/fruitfruit/controller/CompanyController.java
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/CompanyMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/CompanyService.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/user/CompanyMapper.xml
  src/main/resources/sql/user/UserMapper.xml
Labels: ✨ Feature

#50 #15 Fix : 판매자 물품 수정, 삭제 버그 수정
  src/main/java/com/justdo/fruitfruit/controller/ProductController.java
  src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/seller/ProductMapper.xml
Labels: 🐞 BugFix

#53 #52 feat : 회원가입 비밀번호 정규식 조건 설정
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
Labels: ✨ Feature

#54 Feature : #49 판매자 아이디 찾기 완성
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/MainMenu.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/resources/sql/user/UserMapper.xml
Labels: ✨ Feature

#55 #15 Fix : 비회원 물품 조회 기능 결과값 수정
  src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
Labels: 🐞 BugFix

#57 #22 Feat: 추가 시스템 관리자 회원 관리 메뉴
  src/main/java/com/justdo/fruitfruit/controller/ProductController.java
  src/main/java/com/justdo/fruitfruit/controller/SystemController.java
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/SystemMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/SystemService.java
  src/main/java/com/justdo/fruitfruit/view/MainMenu.java
  src/main/java/com/justdo/fruitfruit/view/SystemMenu.java
  src/main/java/com/justdo/fruitfruit/view/SystemResultMessage.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/system/SystemMapper.xml
Labels: ✨ Feature

#59 Feature : #58 회원 비밀번호 찾기 및 재설정 기능 완료
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/MainMenu.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
  src/main/resources/sql/user/UserMapper.xml
Labels: ✨ Feature

#56 #15 Fix : 물품 진행상황 Enum 활용
  src/main/java/com/justdo/fruitfruit/controller/ProductController.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
Labels: 🐞 BugFix

#60 #23 [기능] 시스템 관리자 판매자 관리 메뉴 개발
  src/main/java/com/justdo/fruitfruit/controller/SystemController.java
  src/main/java/com/justdo/fruitfruit/controller/UserController.java
  src/main/java/com/justdo/fruitfruit/model/dao/SystemMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/SystemService.java
  src/main/java/com/justdo/fruitfruit/view/SystemMenu.java
  src/main/java/com/justdo/fruitfruit/view/SystemResultMessage.java
  src/main/resources/sql/system/SystemMapper.xml
Labels: ✨ Feature

#61 창고 관리자 메뉴 기능 개발
  src/main/java/com/justdo/fruitfruit/common/constant/NotificationType.java
  src/main/java/com/justdo/fruitfruit/controller/WarehouseController.java
  src/main/java/com/justdo/fruitfruit/model/dao/WarehouseMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/NotificationDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductLogDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/RequestReleaseDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseResultMessage.java
  src/main/resources/sql/warehouse/WarehouseMapper.xml
Labels: ✨ Feature

#62 #15 Fix : 비회원 물품 조회 조건 설정
  src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
  src/main/resources/sql/user/ProductMapper.xml
Labels: 🐞 BugFix

#64 코드merge
  src/main/java/com/justdo/fruitfruit/controller/InputReader.java
  src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/resources/sql/seller/NotificationMapper.xml
  src/main/resources/sql/user/CompanyMapper.xml
  src/main/resources/sql/user/UserMapper.xml
Labels: 🐞 BugFix

#67 메뉴 수정
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
Labels: 🐞 BugFix

#69 #68 장바구니 수정
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/resources/sql/user/CartMapper.xml
Labels: 📃 Docs

#73 주문추가
  src/main/java/com/justdo/fruitfruit/model/dao/CartMapper.java
  src/main/java/com/justdo/fruitfruit/model/dao/OrderMapper.java
  src/main/java/com/justdo/fruitfruit/model/dao/ProductMapper.java
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/user/CartMapper.xml
  src/main/resources/sql/user/OrderMapper.xml
  src/main/resources/sql/user/ProductMapper.xml
Labels: ✨ Feature

#74 #70 [기능] 시스템 관리자 매출 관리 메뉴 개발
  src/main/java/com/justdo/fruitfruit/model/dao/SystemMapper.java
  src/main/java/com/justdo/fruitfruit/model/dto/SalesDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/SystemService.java
  src/main/java/com/justdo/fruitfruit/run/Run.java
  src/main/java/com/justdo/fruitfruit/view/SystemMenu.java
  src/main/resources/sql/system/SystemMapper.xml
Labels: ✨ Feature

#78 수정 DTO toString
  src/main/java/com/justdo/fruitfruit/model/dto/OrderDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/UserDTO.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
Labels: 🔨 Refactor

#81 찐막
  src/main/java/com/justdo/fruitfruit/model/dto/OrderDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/UserDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/UserService.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/user/OrderMapper.xml
  src/main/resources/sql/warehouse/WarehouseMapper.xml
Labels: 📃 Docs

#82 수정
  src/main/java/com/justdo/fruitfruit/model/dto/NotificationDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/service/SellerService.java
  src/main/java/com/justdo/fruitfruit/view/UserMenu.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/sql/seller/NotificationMapper.xml
Labels: 🐞 BugFix

#84 FIX : company 조회 조건에 delete_yn추가, CompanyDTO의 toString변경
  src/main/java/com/justdo/fruitfruit/model/dto/CompanyDTO.java
  src/main/resources/sql/system/SystemMapper.xml
  src/main/resources/sql/user/CompanyMapper.xml
Labels: 🐞 BugFix

#86 #72 Fix : 통합테스트 케이스 오류 수정 ver2
  src/main/java/com/justdo/fruitfruit/common/constant/Auth.java
  src/main/java/com/justdo/fruitfruit/model/dto/CompanyDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
  src/main/java/com/justdo/fruitfruit/model/dto/UserDTO.java
  src/main/resources/sql/seller/ProductMapper.xml
  src/main/resources/sql/system/SystemMapper.xml
Labels: 🐞 BugFix
